# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HSA
                                 A QGIS plugin
 This plugin add to the processing toolbox a geoprocess to compute the Hydraulic Average Slope
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-04
        copyright            : (C) 2022 by Salvatore Fiandaca, Antonio Cotroneo, Federico Gianoli
        email                : gianoli.federico@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Salvatore Fiandaca, Antonio Cotroneo, Federico Gianoli'
__date__ = '2022-03-04'
__copyright__ = '(C) 2022 by Salvatore Fiandaca, Antonio Cotroneo, Federico Gianoli'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HSA class from file HSA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hsa import HSAPlugin
    return HSAPlugin()
